dipsycat_fb_social_homepage:
    path:     /
    defaults: { _controller: DipsycatFbSocialBundle:Main:index }

_security_login:
    path:  /login
    defaults: { _controller: DipsycatFbSocialBundle:Security:login }

_security_check:
    path:  /login_check

_security_logout:
    path:  /logout

dipsycat_fb_social_admin_home:
    path:  /admin/
    defaults: { _controller: DipsycatFbSocialBundle:Admin:index }
    
dipsycat_fb_social_user_edit:
    path:  /edit
    defaults: { _controller: DipsycatFbSocialBundle:User:getUserForm }
    
dipsycat_fb_social_user_edit_post:
    path:  /edit_post
    defaults: { _controller: DipsycatFbSocialBundle:User:postUserForm }
    
dipsycat_fb_social_friend_list:
    path:  /friends
    defaults: { _controller: DipsycatFbSocialBundle:User:getFriends }

dipsycat_fb_social_conversation_list:
    path:  /conversations
    defaults: { _controller: DipsycatFbSocialBundle:Conversation:index }

dipsycat_fb_social_conversation:
    path:  /conversation/{id}
    defaults: { _controller: DipsycatFbSocialBundle:Conversation:getConversation }
    requirements:
            id: '\d+'